### ISSUE TITLE
The documentation shows the fields I need to submit. But "API" responds that the fields are invalid.

### ISSUE THREAD

**Issue by malware8** [wuhewuhe/bybit.go.api#28]
The documentation shows the fields I need to submit. But "API" responds that the fields are invalid.

[Link to documentation](https://bybit-exchange.github.io/docs/api-explorer/v5/asset/transferable-coin)

`func (c *Client) GetTransferableCoin(ctx context.Context, auth Authorization, request GetTransferableCoinRequest) (*GetTransferableCoinResponse, error) {
	client := sdk.NewBybitHttpClient(auth.ApiKey, auth.SecKey, sdk.WithBaseURL(sdk.TESTNET))
	params := map[string]interface{}{"fromAccountType": request.FromAccountType, "toAccountType": request.ToAccountType}

	client.Debug = true

	logrus.Info("Request Params: ", params)

	response, err := client.NewAssetService(params).GetTransferableCoin(ctx, sdk.WithRecvWindow(c.cfg.WithRecvWindow))
	if err != nil {
		logrus.Error("Bybit SDK - get transferable coin failed with error: ", err.Error())
		if strings.TrimSpace(response.RetMsg) != "" {
			return nil, NewBybitError(response.RetMsg)
		}
		return nil, err
	}

	logrus.Info("test result", response)
	return &GetTransferableCoinResponse{}, nil
}`

log output:
bybit.api.go2024/02/09 16:58:58 response body: {"retCode":131203,"retMsg":"request parameter err: fromAccountType invalid",

**Comment by malware8** [comment]
func (c *Client) GetTransferableCoin(ctx context.Context, auth Authorization, request GetTransferableCoinRequest) (*GetTransferableCoinResponse, error) {
	client := sdk.NewBybitHttpClient(auth.ApiKey, auth.SecKey, sdk.WithBaseURL(sdk.TESTNET))

	result := &GetTransferableCoinResponse{}

	params := map[string]interface{}{
		"fromAccountType": request.FromAccountType,
		"toAccountType":   request.ToAccountType,
	}

	response, err := client.NewAssetService(params).GetTransferableCoin(ctx, sdk.WithRecvWindow(c.cfg.WithRecvWindow))
	if err != nil {
		logrus.Error("Bybit SDK - get transferable coin failed with error: ", err.Error())
		if strings.TrimSpace(response.RetMsg) != "" {
			return nil, NewBybitError(response.RetMsg)
		}
		return nil, err
	}

	err = result.FromInterface(response.Result)
	if err != nil {
		return nil, err
	}
	return result, nil
}

![image](https://github.com/wuhewuhe/bybit.go.api/assets/53379527/b1c4fbd7-ee3c-4bc2-b4f0-ab567151f0e1)



![image](https://github.com/wuhewuhe/bybit.go.api/assets/53379527/c48845f6-3f49-4598-a4c8-820f77d44502)

but in the programming language "Python" it works fine

![image](https://github.com/wuhewuhe/bybit.go.api/assets/53379527/d1f4428d-9736-48f0-9c8e-20661dd44750)

**Comment by malware8** [comment]
![image](https://github.com/wuhewuhe/bybit.go.api/assets/53379527/a7a42dd3-6166-41f2-9916-135e9245c0d5)

**Comment by wuhewuhe** [comment]
fix it and publish on v1.0.2
