### ISSUE TITLE
[bug] Rate limit error parsing breaking for MarketKlineService

### ISSUE THREAD

**Issue by sanketBijawe** [wuhewuhe/bybit.go.api#32]
Hi, I'm hitting NewMarketKlineService for historical klines. I'm hitting rate limit on the same but the client simply returns `<APIError> code=0, msg=`. I can see an rate limiting error on enabling debug logs for the client. The error parsing is breaking and hence client doesn't return any specific error on hitting rate limit. It would be a great help for handling rate limits if specific error code/message is returned on hitting rate limit.

**Comment by wuhewuhe** [comment]
this is another issue not link to rate limit.
market request only have ip limit not rate limit
